# Location of my dotfiles
DOTFILES=$HOME/.dotfiles

# Update PATH
path=(
	/usr/local/{bin,sbin}
	$DOTFILES/scripts
	$path
)
typeset -U path

# Configure bullet-train
BULLETTRAIN_PROMPT_ORDER=(
	time
	dir
	nvm
	perl
	git
	status
)

BULLETTRAIN_IS_SSH_CLIENT=true
BULLETTRAIN_DIR_EXTENDED=2
# bullet-train git colors
BULLETTRAIN_GIT_COLORIZE_DIRTY=true
BULLETTRAIN_GIT_COLORIZE_DIRTY_BG_COLOR=yellow



# change the size of history files
COMPLETION_WAITING_DOTS="true"
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE

# Shell
export CLICOLOR=1;
export EDITOR='vim'
export PAGER='less'


if [ ! $TERM = dumb ]; then
	ZGEN_AUTOLOAD_COMPINIT=true

	# If user is root it can have some issues with access to competition files
	if [[ "${USER}" == "root" ]]; then
		ZGEN_AUTOLOAD_COMPINIT=false
	fi

	# load zgen
	source $DOTFILES/zgen/zgen.zsh

	# configure zgen
	if ! zgen saved; then

		# zgen will load oh-my-zsh and downoad it if required
		zgen oh-my-zsh

		# list of plugins from zsh I use
		# see https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins
		zgen oh-my-zsh plugins/brew
		zgen oh-my-zsh plugins/composer
		zgen oh-my-zsh plugins/docker
		zgen oh-my-zsh plugins/git
		zgen oh-my-zsh plugins/git-extras
		zgen oh-my-zsh plugins/gitignore
		zgen oh-my-zsh plugins/node
		zgen oh-my-zsh plugins/npm
		zgen oh-my-zsh plugins/osx
		zgen oh-my-zsh plugins/sudo
		zgen oh-my-zsh plugins/vundle

		# https://github.com/zsh-users/zsh-completions
		zgen load zsh-users/zsh-completions src

		# Actual ZSH plugins
		# see: https://github.com/unixorn/awesome-zsh-plugins

		# list of plugins from zsh I use

		# load https://github.com/bhilburn/powerlevel9k theme for zsh
		# zgen load bhilburn/powerlevel9k powerlevel9k

		# this takes conrol, so load last
		zgen save
	fi

fi

#Load bullet-train, set the theme
zgen oh-my-zsh
zgen load caiogondim/bullet-train-oh-my-zsh-theme bullet-train
ZSH_THEME="bullet-train" #"geometry"

#Establish environmental variables
# Path to your oh-my-zsh installation.
export ZSH=/Users/bryan/.oh-my-zsh

# Path to mysql's installation
export PATH=$PATH:/usr/local/mysql/bin

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.



# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git docker zsh-syntax-highlighting)

# User configuration

# export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export NVM_DIR="/Users/Bryan/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
